name: 8 - (Lab15) Workflow CI/CD Advanced Terraform

on:
  push:
    branches:
      - Dev-Stan
  workflow_dispatch:

jobs:

  Terraform-Lint-Plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out du repository
        uses: actions/checkout@v2

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.1.7
       
      # https://github.com/marketplace/actions/tfsec-action  
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.2
        with:
          version: v1.1.2
          soft_fail: true 
      
      # https://github.com/marketplace/actions/run-tfsec-pr-commenter
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}
          tfsec_args: --soft-fail
          tfsec_version: v1.1.2
          
